Fix/euk subwf remove alignment
EBI-Metagenomics/genomes-generation pull request #26
Opened 2024-04-29 16:12 UTC by KateSakharova

Removed alignment euk MAG to reads to calculate depth because it can be re-used from initial metabat run.

MultiQC:
- Add FasqQC
- Add MultiQC
- added stats for busco and samtools to MutliQC report

2024-05-03 08:57 UTC, Ales-ibt approved these changes
It looks Ok to me, It is great you rid of unnecessary bam files. I think most of the commits are to add idxstats to the multiqc report, which is useful to track where the reads goes. I like the multiMap function, it makes the code more clean and tidy.

2024-05-07 09:45 UTC, chrisAta approved these changes
looks good to me thank you!

2024-05-08 14:09 UTC, Ales-ibt approved these changes
Minor changes looks Ok to me :D

2024-05-08 15:23 UTC, mberacochea requested changes
Thanks @KateSakharova I left some minor comments

2024-05-08 15:23 UTC, mberacochea commented on assets/multiqc_config.yml
> +      name: Samtools. Alignment reads on assembly
```suggestion
      name: Samtools - Stats from reads aligned to the assembly
```

2024-05-08 15:23 UTC, mberacochea commented on assets/multiqc_config.yml
> +      name: Samtools. CONCOCT bins alignment on assembly
```suggestion
      name: Samtools - Stats from CONCOCT bins aligned to the assembly
```

2024-05-08 15:23 UTC, mberacochea commented on assets/multiqc_config.yml
> +      name: Samtools. MetaBAT2 bins alignment on assembly
```suggestion
      name: Samtools - Stats from MetaBAT2 bins aligned to the assembly
```

2024-05-08 15:23 UTC, mberacochea commented on modules/nf-core/multiqc/main.nf
Can you please generate the diff file please `nf-core modules patch multiqc`

2024-05-08 15:23 UTC, mberacochea commented on subworkflows/local/euk_mags_generation.nf
> +    genomes                   = GZIP_MAGS.out.compressed.collect()
Do we need to use `.collect()` here?

2024-05-15 13:21 UTC, Ales-ibt commented on modules/local/align_bwa/main.nf
If you have multiple rounds of decontamination, you can use the meta.id of the reference to differentiate them

2024-05-16 11:58 UTC, merged